### ISSUE TITLE
Feature request: regex filename inclusion

### ISSUE THREAD

**Issue by b-zurg** [fabriciobastian/download-release-asset-action#1]
One common possibility is to have multiple assets that you want to download with an action.  

Instead of doing a literal string comparison for the filename it could be a regular expression comparison - this would not break existing usage but also allow more flexible inclusion with multiple assets.

**Comment by fabriciobastian** [comment]
@b-zurg,

Thanks for the suggestion. How many assets do you need to download in your case? In which case do you think that this would be useful?

I believe that the most common case is to download specific assets (since most releases have very few assets?). And since there is no guarantee that the asset names will have any relations, then I am not sure that I see how a regexp  would help (except in very specific cases).

If you have to download a large number of assets, then maybe the solution for you would be to download the whole release in a folder, copy the assets that you want and then delete the rest?

What I have been doing, is to pack the files that I need in a release asset (e.g. zip file) and then download it. In this case I own both repositories, of course - so I can control the release and create the assets that I need.
